# Generated by Django 2.1.2 on 2018-10-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abbreviation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=1)),
                ('second', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name': 'Abbreviation',
                'verbose_name_plural': 'Abbreviations',
            },
        ),
        migrations.CreateModel(
            name='RealObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'RealObject',
                'verbose_name_plural': 'RealObjects',
            },
        ),
        migrations.AddField(
            model_name='abbreviation',
            name='real_objects',
            field=models.ManyToManyField(to='cubeapp.RealObject'),
        ),
    ]
