# Generated by Django 2.1.2 on 2018-10-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubeapp', '0003_realobject_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='abbreviation',
            name='default_realobject',
            field=models.ForeignKey(null=True, on_delete='SET_NULL', related_name='default_to_abbreviation', to='cubeapp.RealObject'),
        ),
    ]
