# Generated by Django 2.1.2 on 2018-10-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubeapp', '0004_abbreviation_default_realobject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abbreviation',
            name='default_realobject',
        ),
        migrations.AddField(
            model_name='realobject',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
