# Generated by Django 2.1.2 on 2018-10-19 18:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubeapp', '0007_auto_20181019_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abbreviation',
            name='second',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='illegalletter',
            name='replace',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='illegalletter',
            name='user',
            field=models.ForeignKey(on_delete='CASCADE', related_name='illegalletter', to=settings.AUTH_USER_MODEL),
        ),
    ]
